travis:
  secure:
    BINSTAR_TOKEN: UGZiWlumN9j70GzUdpyHe0cdCiNhWPhyk5poYH8pH4Ecg7IYlhyBO6Y37kxAt05d6CfyowZea/uke0EAfhS13AKUet56pqxGlIvHyg0qcw1mLMAuyfR2uqmpzS3MMk6smjjubR52+vMT9MaebGKcGKKG4rx7tZnSKCTLb/5PkM5t7829Vrd2niU90UPGqfiaxvDbxpTwbbukiCG2GdC2HJhc7egV01mT70+1X2uUM1GyfuztvC480a3ueQbn36vyn9T/H9lwyVLCF/yJFPFPDaDc10Mqq3Z+vEtb7y27ML91sbMSYoNbHGnquTKcbH437PjWnL+RDIOEtp2KDjgzETdeYtRuwqD8gpNfA/LcO+EoTxmJCjfz5Vxw5mFUnIPqRRGk/1DCdW7DJWcVoZSjTUuevp0T/cPpD0oIXerthjyr1mDylGQ6LKTD5yKV0aTu6SqabG67wW9kyWrfNrS1AMkb+x1bwcdXVqF9ltkkmKicaaz34dvD8i+YSRBUJ0sybnzj8Zu1R9Bi0j/EWgDNXlwy7ToBq1eAtLK9K/wQn2JU4YN/hkVhw61r1XjsP01hTcUbKPChOTykBk7+g/G+jztayi1jNMjUPMq+yi4zTVsUF5xPTxvARkYyDrR2Yb21Db95GHdqkfaKqrlGoTyJeExmTZHciF0/VDsoUeXTGn4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
